version: '3.8'
services:
  # 1. تطبيق NestJS
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env # هنا هياخد الـ DATABASE_URL بتاعة Neon
    depends_on:
      - redis_server

  # 2. الريديس (لأنه لسه محلي على جهازك أو السيرفر)
  redis_server:
    image: redis:alpine
    ports:
      - "6379:6379"